version: "2"

# start the forward server
listen: ":2999"

services:

  httpbin:
    path_prefix: /httpbin
    backend: https://httpbin.org
    middlewares:
    - name: logger
    - name: debug

  openai:
    path_prefix: /v1
    backend: https://api.openai.com/v1
    middlewares:
    - name: logger
    - name: debug
    - name: openai
      etcd_addr: http://etcd:2379
      # limit_day: 100
